### ISSUE TITLE
ImportError: cannot import name 'formatargspec' from 'inspect'

### ISSUE THREAD

**Issue by pdmct** [geekscape/aiko_services#11]
ENV:  
Mac OSX 14.4.1
Python 3.12.3

PROBLEM:
Version 1.12.1 of wrapt tries to import missing (deprecated since python 3.5) functions as per the following stack trace:
```(venv) ➜  scripts git:(master) ✗ ./system_start.sh
Already started: /opt/homebrew/opt/mosquitto/sbin/mosquitto
Starting: aiko_registrar
Traceback (most recent call last):
  File "/Users/me/Documents/projects/llms/aiko_services/venv/bin/aiko_dashboard", line 5, in <module>
    from aiko_services.main.dashboard import main
  File "/Users/me/Documents/projects/llms/aiko_services/src/aiko_services/__init__.py", line 1, in <module>
    import aiko_services.main
  File "/Users/me/Documents/projects/llms/aiko_services/src/aiko_services/main/__init__.py", line 40, in <module>
    from .proxy import ProxyAllMethods, is_callable, proxy_trace
  File "/Users/me/Documents/projects/llms/aiko_services/src/aiko_services/main/proxy.py", line 31, in <module>
    import wrapt
  File "/Users/me/Documents/projects/llms/aiko_services/venv/lib/python3.12/site-packages/wrapt/__init__.py", line 10, in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "/Users/me/Documents/projects/llms/aiko_services/venv/lib/python3.12/site-packages/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py). Did you mean: 'formatargvalues'?
```
Upgrading the version of wrapt to 1.16.0 (current latest) seems to resolve these issue but I haven't tested it thoroughly.

**Comment by geekscape** [comment]
Thanks !  Have updated [pyproject.toml](https://github.com/geekscape/aiko_services/blob/master/pyproject.toml#L46) for `wrapt 1.16.0` ... and tested on Linux (Ubuntu) and Mac OS X Sonoma 14.5 using Python 3.12.3.

Fixed by _master_ branch commit [d4ee76a](https://github.com/geekscape/aiko_services/commit/d4ee76ad93d94f4974f876dd4e59c4fc5c64bf8e)
